### ISSUE TITLE
Issue with AWS DeepRacer simulator

### ISSUE THREAD

**Issue by billchenxi** [aws-robotics/aws-robomaker-sample-application-deepracer#25] opened 2019-05-14 14:34 UTC
Hi there, 
hope you are doing well. I have a horrible week using AWS DeepRacer to train my model. What my issue is that the simulator starts always at the (0,0) coordinate and not on the track I supposed to train. See the images below
<img width="1067" alt="Problem" src="https://user-images.githubusercontent.com/986935/57706357-9400c980-7633-11e9-882e-a8b3bfa6cec1.png">
and 
<img width="1590" alt="problem2" src="https://user-images.githubusercontent.com/986935/57706389-a24ee580-7633-11e9-8f67-2e3e8acc0305.png">
After about 30 minutes, the car was still seeing only the grasses around. Is there something wrong with the simulator???

If there's a bug, please stop this gimmick, because we have to pay money for using the AWS!!!

Thanks,
Bill

**Comment by adam-dunc** [comment] 2019-05-14 17:41
Hi Bill, we are very sorry to hear you are having a bad experience with the DeepRacer. 

From the screenshots, It looks like you are running this from the DeepRacer console, is that correct? We want to confirm you did not run the sample application in RoboMaker and you did not take the code here from github and modify/run it independently to narrow down the troubleshooting. Can you please confirm the exact steps you took to get to this scenario? This is the first time this has been reported and we've been unable to reproduce it. 

We will also likely need your AWS account information to try to investigate further into the logs if we are unable to reproduce. If you'd like to send us any information about your account please email: ros-contributions@amazon.com

-Adam

**Comment by madan96** [comment] 2019-06-02 10:08
Just in case if you were using the local training launch file for this, I was encountering the same issue. In my case, I had forgot to set the `MARKOV_PRESET_FILE` environment variable to `deepracer.py`. Hope it helps :slightly_smiling_face:

**Comment by nburek** [comment] 2019-06-11 15:55
@billchenxi let us know if @madan96's suggestion solves the issue for you. In the mean time, I'm going to close this issue as there is not enough information for us to reproduce it at the moment. Please reopen if you are still experiencing this issue or have additional information on how you were running the simulation that we can use to try to reproduce.

**Closed as completed by nburek** 2019-06-11 15:55 UTC
